name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main # o master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Puedes especificar una versión como '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt # o pip install sphinx sphinx-rtd-theme

      - name: Build Documentation
        run: |
          sphinx-build -b html docs _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html # La carpeta de salida por defecto de Sphinx